##
## EPITECH PROJECT, 2019
## B-FUNC
## File description:
## Makefile
##

all:
	stack build --copy-bins --local-bin-path .
	mv imagecomp-exe imagecomp

clean:
	stack clean

fclean: clean
	rm imagecomp

re: fclean all