##
## EPITECH PROJECT, 2019
## B-FUNC
## File description:
## Makefile
##

all:
	stack build --copy-bins --local-bin-path .
	mv DeBruijn-exe DeBruijn

clean:
	stack clean

fclean: clean
	rm DeBruijn

re: fclean all